# Generated by Django 3.2.17 on 2023-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.SmallIntegerField(choices=[(0, 'Venda'), (1, 'Empréstimo')]),
        ),
    ]
