# Generated by Django 3.2 on 2023-01-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.SmallIntegerField(blank=True, choices=[(1, 'Unidade 01'), (2, 'Unidade 02')])),
                ('nome', models.CharField(max_length=200, verbose_name='Cliente')),
                ('razaosocial', models.CharField(blank=True, max_length=200, verbose_name='Razão Social')),
                ('tipo', models.SmallIntegerField(choices=[(0, 'Pessoa Física'), (1, 'Pessoa Jurídica')])),
                ('cpfcnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('rgie', models.CharField(blank=True, max_length=14, null=True, verbose_name='Insc.Estadual')),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=6, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(default='Belo Horizonte', max_length=250)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='MG', max_length=2, verbose_name='UF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone1', models.CharField(max_length=15, verbose_name='Telefone')),
                ('phone2', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('delivery', models.BooleanField(default=False, verbose_name='Delivery')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='ClienteTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'tabela',
            },
        ),
    ]
