# Generated by Django 3.2.12 on 2023-03-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='filial',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Unidade 01'), (2, 'Unidade 02'), (3, 'Unidade 03')]),
        ),
    ]
